# Yahoo Finance 캘린더 크롤링을 위한 CSS 클래스 선택자 정의
# 마지막 업데이트: 2024-03-17

common:
  # 페이지네이션 관련 클래스
  pagination:
    results_text: 'type-body-sm-reg'  # 결과 수 표시 텍스트
    next_button: '[data-testid="next-page-button"]'  # 다음 페이지 버튼

  # 테이블 관련 클래스
  table:
    container: 'table-container'
    row: 'BdT'  # 테이블 행 구분선

# 각 캘린더 타입별 특화된 클래스
earnings:
  symbol_link: 'loud-link'  # 심볼 링크
  cells:
    symbol: 'div'  # 심볼이 링크가 아닐 경우의 컨테이너
    surprise: 'p'  # 서프라이즈 비율 컨테이너

economic:
  cells:
    event: 'div'
    country: 'div'

ipo:
  symbol_link: 'loud-link'
  cells:
    symbol: 'div'
    exchange: 'div'

splits:
  symbol_link: 'loud-link'
  cells:
    symbol: 'div'
    ratio: 'div'

# 클래스 변경 이력
version_history:
  - date: '2024-03-17'
    changes:
      - 'type-body-sm-reg 클래스 추가'
      - 'loud-link 클래스 확인'
      - 'BdT 행 구분선 클래스 확인' 